export interface LangTheme {
  dark: string;
  light: string;
  color: string;
}

export const LANG_THEMES: Record<string, LangTheme> = {
  python: { dark: 'material', light: 'idea', color: '#3776AB' },
  python2: { dark: 'material', light: 'idea', color: '#3776AB' },
  pypy: { dark: 'material', light: 'idea', color: '#3776AB' },
  c: { dark: 'dracula', light: 'eclipse', color: '#A8B9CC' },
  'c++': { dark: 'dracula', light: 'eclipse', color: '#00599C' },
  java: { dark: 'darcula', light: 'idea', color: '#ED8B00' },
  kotlin: { dark: 'darcula', light: 'idea', color: '#7F52FF' },
  scala: { dark: 'darcula', light: 'idea', color: '#DC322F' },
  groovy: { dark: 'darcula', light: 'idea', color: '#4298B8' },
  javascript: { dark: 'monokai', light: 'mdn-like', color: '#F7DF1E' },
  typescript: { dark: 'monokai', light: 'mdn-like', color: '#3178C6' },
  node: { dark: 'monokai', light: 'mdn-like', color: '#339933' },
  deno: { dark: 'monokai', light: 'mdn-like', color: '#070707' },
  coffeescript: { dark: 'monokai', light: 'mdn-like', color: '#2F2A2B' },
  rust: { dark: 'gruvbox-dark', light: 'idea', color: '#CE422B' },
  go: { dark: 'nord', light: 'neat', color: '#00ACD7' },
  bash: { dark: '3024-night', light: 'eclipse', color: '#4EAA25' },
  dash: { dark: '3024-night', light: 'eclipse', color: '#4EAA25' },
  awk: { dark: '3024-night', light: 'eclipse', color: '#4EAA25' },
  gawk: { dark: '3024-night', light: 'eclipse', color: '#4EAA25' },
  fortran: { dark: 'oceanic-next', light: 'idea', color: '#4E8CA5' },
  d: { dark: 'oceanic-next', light: 'idea', color: '#BA595E' },
  haskell: { dark: 'dracula', light: 'eclipse', color: '#5D4F85' },
  ocaml: { dark: 'darcula', light: 'idea', color: '#EC6813' },
  ruby: { dark: 'dracula', light: 'eclipse', color: '#CC342D' },
  crystal: { dark: 'dracula', light: 'eclipse', color: '#000100' },
  lua: { dark: 'dracula', light: 'eclipse', color: '#000080' },
  perl: { dark: 'darcula', light: 'idea', color: '#39457E' },
  php: { dark: 'darcula', light: 'idea', color: '#8892BF' },
  pascal: { dark: 'darcula', light: 'idea', color: '#E3F171' },
  csharp: { dark: 'darcula', light: 'idea', color: '#178600' },
  'csharp.net': { dark: 'darcula', light: 'idea', color: '#178600' },
  'fsharp.net': { dark: 'darcula', light: 'idea', color: '#B845FC' },
  'basic.net': { dark: 'darcula', light: 'idea', color: '#945DB7' },
  basic: { dark: 'darcula', light: 'idea', color: '#945DB7' },
  fsi: { dark: 'darcula', light: 'idea', color: '#B845FC' },
  swift: { dark: 'nord', light: 'neat', color: '#F05138' },
  dart: { dark: 'darcula', light: 'idea', color: '#00B4AB' },
  julia: { dark: 'dracula', light: 'eclipse', color: '#9558B2' },
  elixir: { dark: 'dracula', light: 'eclipse', color: '#6E4A7E' },
  erlang: { dark: 'dracula', light: 'eclipse', color: '#B83998' },
  nim: { dark: 'nord', light: 'neat', color: '#FFE953' },
  zig: { dark: 'gruvbox-dark', light: 'idea', color: '#F7A41D' },
  vlang: { dark: 'nord', light: 'neat', color: '#5D87BF' },
  clojure: { dark: 'darcula', light: 'idea', color: '#5881D8' },
  racket: { dark: 'darcula', light: 'idea', color: '#22228F' },
  lisp: { dark: 'darcula', light: 'idea', color: '#3FB68B' },
  prolog: { dark: 'dracula', light: 'eclipse', color: '#74283C' },
  cobol: { dark: 'darcula', light: 'idea', color: '#0061A8' },
  rscript: { dark: 'darcula', light: 'idea', color: '#276DC3' },
  powershell: { dark: 'darcula', light: 'idea', color: '#012456' },
  pwsh: { dark: 'darcula', light: 'idea', color: '#012456' },
  nasm: { dark: '3024-night', light: 'eclipse', color: '#6E4A7E' },
  nasm64: { dark: '3024-night', light: 'eclipse', color: '#6E4A7E' },
  sqlite3: { dark: 'darcula', light: 'idea', color: '#003B57' },
  brainfuck: { dark: 'monokai', light: 'mdn-like', color: '#2F2A2B' },
  befunge93: { dark: 'monokai', light: 'mdn-like', color: '#FF6B6B' },
  lolcode: { dark: 'monokai', light: 'mdn-like', color: '#FFB347' },
  smalltalk: { dark: 'darcula', light: 'idea', color: '#596706' },
  forth: { dark: 'darcula', light: 'idea', color: '#341708' },
  forte: { dark: 'darcula', light: 'idea', color: '#7B7B7B' },
  freebasic: { dark: 'darcula', light: 'idea', color: '#867DB1' },
  octave: { dark: 'darcula', light: 'idea', color: '#DA252C' },
  default: { dark: 'monokai', light: 'idea', color: '#6B7280' },
};

export function getLangTheme(lang: string): LangTheme {
  return LANG_THEMES[lang] || LANG_THEMES.default;
}

export const LANG_MODES: Record<string, string> = {
  c: 'text/x-csrc',
  'c++': 'text/x-c++src',
  java: 'text/x-java',
  kotlin: 'text/x-kotlin',
  scala: 'text/x-scala',
  groovy: 'text/x-groovy',
  python: 'text/x-python',
  python2: 'text/x-python',
  pypy: 'text/x-python',
  javascript: 'text/javascript',
  typescript: 'text/typescript',
  node: 'text/javascript',
  deno: 'text/typescript',
  coffeescript: 'text/x-coffeescript',
  rust: 'text/x-rustsrc',
  go: 'text/x-go',
  bash: 'text/x-sh',
  dash: 'text/x-sh',
  awk: 'text/x-sh',
  gawk: 'text/x-sh',
  fortran: 'text/x-fortran',
  d: 'text/x-d',
  haskell: 'text/x-haskell',
  ocaml: 'text/x-ocaml',
  'fsharp.net': 'text/x-fsharp',
  fsi: 'text/x-fsharp',
  ruby: 'text/x-ruby',
  crystal: 'text/x-crystal',
  lua: 'text/x-lua',
  perl: 'text/x-perl',
  php: 'text/x-php',
  pascal: 'text/x-pascal',
  csharp: 'text/x-csharp',
  'csharp.net': 'text/x-csharp',
  'basic.net': 'text/x-vb',
  basic: 'text/x-vb',
  erlang: 'text/x-erlang',
  clojure: 'text/x-clojure',
  racket: 'text/x-scheme',
  lisp: 'text/x-common-lisp',
  sqlite3: 'text/x-sqlite',
  julia: 'text/x-julia',
  rscript: 'text/x-rsrc',
  powershell: 'text/x-powershell',
  pwsh: 'text/x-powershell',
  cobol: 'text/x-cobol',
  swift: 'text/x-swift',
  dart: 'text/x-dart',
  brainfuck: 'text/x-brainfuck',
  smalltalk: 'text/x-stsrc',
  forth: 'text/x-forth',
  forte: 'text/x-factor',
  nasm: 'text/x-gas',
  nasm64: 'text/x-gas',
  octave: 'text/x-octave',
};

export interface LangExample {
  ext: string;
  stdin: string;
  code: string;
}

export const EXAMPLES: Record<string, LangExample> = {
  python: { ext: 'py', stdin: '7\n', code: 'n = int(input())\nprint(n * n)\n' },
  python2: { ext: 'py', stdin: '7\n', code: 'n = int(raw_input())\nprint n * n\n' },
  pypy: { ext: 'py', stdin: '7\n', code: 'n = int(input())\nprint(n * n)\n' },
  c: {
    ext: 'c',
    stdin: '7\n',
    code: '#include <stdio.h>\nint main() {\n    int n;\n    scanf("%d", &n);\n    printf("%d\\n", n * n);\n    return 0;\n}\n',
  },
  'c++': {
    ext: 'cpp',
    stdin: '7\n',
    code: '#include <bits/stdc++.h>\nusing namespace std;\nint main() {\n    ios_base::sync_with_stdio(false);\n    cin.tie(NULL);\n    int n;\n    cin >> n;\n    cout << n * n << "\\n";\n    return 0;\n}\n',
  },
  d: {
    ext: 'd',
    stdin: '7\n',
    code: 'import std.stdio;\nimport std.conv;\nvoid main() {\n    int n = readln().strip().to!int;\n    writeln(n * n);\n}\n',
  },
  java: {
    ext: 'java',
    stdin: '7\n',
    code: 'import java.util.Scanner;\npublic class Main {\n    public static void main(String[] args) {\n        Scanner sc = new Scanner(System.in);\n        int n = sc.nextInt();\n        System.out.println(n * n);\n    }\n}\n',
  },
  kotlin: { ext: 'kt', stdin: '7\n', code: 'fun main() {\n    val n = readLine()!!.trim().toInt()\n    println(n * n)\n}\n' },
  scala: { ext: 'scala', stdin: '7\n', code: 'object Main extends App {\n  val n = scala.io.StdIn.readInt()\n  println(n * n)\n}\n' },
  groovy: { ext: 'groovy', stdin: '7\n', code: 'def n = new Scanner(System.in).nextInt()\nprintln n * n\n' },
  csharp: {
    ext: 'cs',
    stdin: '7\n',
    code: 'using System;\nclass Program {\n    static void Main() {\n        int n = int.Parse(Console.ReadLine());\n        Console.WriteLine(n * n);\n    }\n}\n',
  },
  'csharp.net': {
    ext: 'cs',
    stdin: '7\n',
    code: 'using System;\nclass Program {\n    static void Main() {\n        int n = int.Parse(Console.ReadLine());\n        Console.WriteLine(n * n);\n    }\n}\n',
  },
  'fsharp.net': { ext: 'fs', stdin: '7\n', code: 'open System\nlet n = Console.ReadLine() |> int\nprintfn "%d" (n * n)\n' },
  'basic.net': {
    ext: 'vb',
    stdin: '7\n',
    code: 'Imports System\nModule Program\n    Sub Main()\n        Dim n As Integer = Integer.Parse(Console.ReadLine())\n        Console.WriteLine(n * n)\n    End Sub\nEnd Module\n',
  },
  basic: {
    ext: 'vb',
    stdin: '7\n',
    code: 'Imports System\nModule Program\n    Sub Main()\n        Dim n As Integer = Integer.Parse(Console.ReadLine())\n        Console.WriteLine(n * n)\n    End Sub\nEnd Module\n',
  },
  fsi: { ext: 'fsx', stdin: '7\n', code: 'let n = System.Console.ReadLine() |> int\nprintfn "%d" (n * n)\n' },
  javascript: {
    ext: 'js',
    stdin: '7\n',
    code: "process.stdin.resume();\nprocess.stdin.setEncoding('utf8');\nlet _in = '';\nprocess.stdin.on('data', d => _in += d);\nprocess.stdin.on('end', () => {\n    const lines = _in.trim().split('\\n');\n    const n = parseInt(lines[0]);\n    console.log(n * n);\n});\n",
  },
  node: {
    ext: 'js',
    stdin: '7\n',
    code: "process.stdin.resume();\nprocess.stdin.setEncoding('utf8');\nlet _in = '';\nprocess.stdin.on('data', d => _in += d);\nprocess.stdin.on('end', () => {\n    const lines = _in.trim().split('\\n');\n    const n = parseInt(lines[0]);\n    console.log(n * n);\n});\n",
  },
  typescript: {
    ext: 'ts',
    stdin: '7\n',
    code: 'import * as fs from "fs";\nconst n = parseInt(fs.readFileSync("/dev/stdin","utf8").trim());\nconsole.log(n * n);\n',
  },
  deno: {
    ext: 'ts',
    stdin: '7\n',
    code: 'const text = new TextDecoder().decode(Deno.readAllSync(Deno.stdin));\nconst n = parseInt(text.trim());\nconsole.log(n * n);\n',
  },
  coffeescript: {
    ext: 'coffee',
    stdin: '7\n',
    code: "n = parseInt require('fs').readFileSync('/dev/stdin','utf8').trim()\nconsole.log n * n\n",
  },
  rust: {
    ext: 'rs',
    stdin: '7\n',
    code: 'use std::io::{self, BufRead};\nfn main() {\n    let stdin = io::stdin();\n    let n: i64 = stdin.lock().lines().next().unwrap().unwrap()\n        .trim().parse().unwrap();\n    println!("{}", n * n);\n}\n',
  },
  go: { ext: 'go', stdin: '7\n', code: 'package main\nimport "fmt"\nfunc main() {\n    var n int\n    fmt.Scan(&n)\n    fmt.Println(n * n)\n}\n' },
  zig: {
    ext: 'zig',
    stdin: '7\n',
    code: 'const std = @import("std");\npub fn main() !void {\n    const stdin = std.io.getStdIn().reader();\n    var buf: [64]u8 = undefined;\n    const line = try stdin.readUntilDelimiter(&buf, \'\\n\');\n    const n = try std.fmt.parseInt(i64, std.mem.trim(u8, line, "\\r\\n "), 10);\n    const out = std.io.getStdOut().writer();\n    try out.print("{}\\n", .{n * n});\n}\n',
  },
  vlang: { ext: 'v', stdin: '7\n', code: 'import os\nfn main() {\n    n := os.get_line().trim_space().int()\n    println(n * n)\n}\n' },
  nim: { ext: 'nim', stdin: '7\n', code: 'import strutils\nlet n = parseInt(readLine(stdin))\necho n * n\n' },
  haskell: { ext: 'hs', stdin: '7\n', code: 'main :: IO ()\nmain = do\n    n <- readLn :: IO Int\n    print (n * n)\n' },
  ocaml: {
    ext: 'ml',
    stdin: '7\n',
    code: 'let () =\n  let n = Scanf.scanf " %d" (fun x -> x) in\n  Printf.printf "%d\\n" (n * n)\n',
  },
  clojure: { ext: 'clj', stdin: '7\n', code: '(let [n (Integer/parseInt (read-line))]\n  (println (* n n)))\n' },
  racket: { ext: 'rkt', stdin: '7\n', code: '#lang racket\n(define n (read))\n(displayln (* n n))\n' },
  lisp: { ext: 'lisp', stdin: '7\n', code: '(let ((n (read)))\n  (format t "~a~%" (* n n)))\n' },
  elixir: { ext: 'ex', stdin: '7\n', code: 'n = IO.read(:line) |> String.trim() |> String.to_integer()\nIO.puts(n * n)\n' },
  erlang: {
    ext: 'erl',
    stdin: '7\n',
    code: '-module(main).\n-export([main/0]).\nmain() ->\n    {ok, [N]} = io:fread("", "~d"),\n    io:format("~w~n", [N * N]).\n',
  },
  ruby: { ext: 'rb', stdin: '7\n', code: 'n = gets.chomp.to_i\nputs n * n\n' },
  crystal: { ext: 'cr', stdin: '7\n', code: 'n = gets.not_nil!.chomp.to_i\nputs n * n\n' },
  lua: { ext: 'lua', stdin: '7\n', code: 'local n = tonumber(io.read())\nprint(n * n)\n' },
  perl: { ext: 'pl', stdin: '7\n', code: 'my $n = <STDIN>;\nchomp $n;\nprint $n * $n, "\\n";\n' },
  php: { ext: 'php', stdin: '7\n', code: '<?php\n$n = intval(trim(fgets(STDIN)));\necho $n * $n . "\\n";\n' },
  swift: {
    ext: 'swift',
    stdin: '7\n',
    code: 'import Foundation\nif let line = readLine(), let n = Int(line.trimmingCharacters(in: .whitespaces)) {\n    print(n * n)\n}\n',
  },
  dart: {
    ext: 'dart',
    stdin: '7\n',
    code: "import 'dart:io';\nvoid main() {\n  final n = int.parse(stdin.readLineSync()!);\n  print(n * n);\n}\n",
  },
  julia: { ext: 'jl', stdin: '7\n', code: 'n = parse(Int, readline())\nprintln(n * n)\n' },
  pascal: { ext: 'pas', stdin: '7\n', code: 'var n: Integer;\nbegin\n  readln(n);\n  writeln(n * n);\nend.\n' },
  fortran: {
    ext: 'f90',
    stdin: '7\n',
    code: 'program main\n  implicit none\n  integer :: n\n  read(*,*) n\n  write(*,*) n * n\nend program main\n',
  },
  bash: { ext: 'sh', stdin: '7\n', code: 'read n\necho $((n * n))\n' },
  dash: { ext: 'sh', stdin: '7\n', code: 'read n\necho $((n * n))\n' },
  awk: { ext: 'awk', stdin: '7\n', code: '{ print $1 * $1 }' },
  gawk: { ext: 'awk', stdin: '7\n', code: '{ print $1 * $1 }' },
  rscript: { ext: 'r', stdin: '7\n', code: 'n <- as.integer(readLines("stdin", 1))\ncat(n * n, "\\n")\n' },
  powershell: { ext: 'ps1', stdin: '7\n', code: '$n = [int][Console]::ReadLine()\nWrite-Output ($n * $n)\n' },
  pwsh: { ext: 'ps1', stdin: '7\n', code: '$n = [int][Console]::ReadLine()\nWrite-Output ($n * $n)\n' },
  nasm: {
    ext: 'asm',
    stdin: '7\n',
    code: '; NASM x86-64 hello world\nsection .data\n    msg db "Hello, NASM!", 10\n    len equ $ - msg\nsection .text\n    global _start\n_start:\n    mov rax, 1\n    mov rdi, 1\n    mov rsi, msg\n    mov rdx, len\n    syscall\n    mov rax, 60\n    xor rdi, rdi\n    syscall\n',
  },
  nasm64: {
    ext: 'asm',
    stdin: '7\n',
    code: '; NASM x86-64 hello world\nsection .data\n    msg db "Hello, NASM64!", 10\n    len equ $ - msg\nsection .text\n    global _start\n_start:\n    mov rax, 1\n    mov rdi, 1\n    mov rsi, msg\n    mov rdx, len\n    syscall\n    mov rax, 60\n    xor rdi, rdi\n    syscall\n',
  },
  sqlite3: { ext: 'sql', stdin: '', code: 'SELECT 7 * 7 AS result;\n' },
  prolog: { ext: 'pl', stdin: '7.\n', code: ':- initialization main.\nmain :-\n    read(N),\n    R is N * N,\n    write(R), nl.\n' },
  cobol: {
    ext: 'cob',
    stdin: '7\n',
    code: 'IDENTIFICATION DIVISION.\nPROGRAM-ID. MAIN.\nDATA DIVISION.\nWORKING-STORAGE SECTION.\n01 N PIC 9(9).\n01 R PIC 9(18).\nPROCEDURE DIVISION.\n    ACCEPT N\n    COMPUTE R = N * N\n    DISPLAY R\n    STOP RUN.\n',
  },
  smalltalk: {
    ext: 'st',
    stdin: '7\n',
    code: '| n |\nn := stdin nextLine trimSeparators asInteger.\nTranscript showCr: (n * n) printString.\n',
  },
  forth: { ext: 'forth', stdin: '', code: ': sq dup * . CR ;\n7 sq\nBYE\n' },
  forte: {
    ext: 'factor',
    stdin: '7\n',
    code: 'USE: io\nUSE: kernel\nUSE: math\nUSE: prettyprint\n: main ( -- )\n    readln string>number drop dup * . ;\nmain\n',
  },
  freebasic: { ext: 'bas', stdin: '7\n', code: 'dim n as integer\ninput n\nprint n * n\n' },
  octave: { ext: 'm', stdin: '7\n', code: "n = str2num(input('', 's'));\ndisp(n * n)\n" },
  brainfuck: {
    ext: 'bf',
    stdin: '',
    code: '++++++++++[>+++++++>++++++++++>+++>+<<<<-]>++.>+.+++++++..+++.>++.<<+++++++++++++++.>.+++.------.--------.>+.>.\n',
  },
  befunge93: { ext: 'b93', stdin: '7\n', code: '&:*.\n' },
  lolcode: {
    ext: 'lol',
    stdin: '7\n',
    code: 'HAI 1.2\nI HAS A N ITZ A NUMBR\nGIMMEH N\nI HAS A R ITZ N PRODUKT N\nVISIBLE R\nKTHXBYE\n',
  },
  default: { ext: 'txt', stdin: '', code: '' },
};

export function getExample(lang: string): LangExample {
  return EXAMPLES[lang] || EXAMPLES.default;
}
